In [8]:
import numpy as np

#########3-2
CoordPoints_0 = np.array([[170.], [-170.], [-190.]])
CoordPoints_1 = np.array([[2649.], [-170.], [-190.]])
CoordPoints_2 = np.array([[170.], [-2649.], [-190.]])
CoordPoints_3 = np.array([[2649.], [-2649.], [-190.]])

# ouverture fichier Translation genere a partir de la correlation entre 2-3 d'un meme step: 

Translate=np.array((np.loadtxt('TranslationRef23.txt')),dtype='float')

Gradient=np.mat(Translate[0:3])
GradientReverse=np.mat(Translate[3:6])
AverageRefPos=np.mat(Translate[6]).reshape(3,1)
AverageCurrentPos=np.mat(Translate[7]).reshape(3,1)

# Changement de repere des points (DOWN vers UP)

PointE_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_0-AverageCurrentPos)+AverageRefPos
PointF_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_1-AverageCurrentPos)+AverageRefPos
PointG_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_2-AverageCurrentPos)+AverageRefPos
PointH_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_3-AverageCurrentPos)+AverageRefPos

#########32-1
CoordPoints_0 = PointE_UP
CoordPoints_1 = PointF_UP
CoordPoints_2 = PointG_UP
CoordPoints_3 = PointH_UP

# ouverture fichier Translation genere a partir de la correlation entre 1-2 d'un meme step: 

Translate=np.array((np.loadtxt('TranslationRef12.txt')),dtype='float')

Gradient=np.mat(Translate[0:3])
GradientReverse=np.mat(Translate[3:6])
AverageRefPos=np.mat(Translate[6]).reshape(3,1)
AverageCurrentPos=np.mat(Translate[7]).reshape(3,1)

# Changement de repere des points (DOWN vers UP)

PointE_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_0-AverageCurrentPos)+AverageRefPos
PointF_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_1-AverageCurrentPos)+AverageRefPos
PointG_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_2-AverageCurrentPos)+AverageRefPos
PointH_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_3-AverageCurrentPos)+AverageRefPos

#########321-0
CoordPoints_0 = PointE_UP
CoordPoints_1 = PointF_UP
CoordPoints_2 = PointG_UP
CoordPoints_3 = PointH_UP

# ouverture fichier Translation genere a partir de la correlation entre 0-1 d'un meme step: 

Translate=np.array((np.loadtxt('TranslationRef01.txt')),dtype='float')

Gradient=np.mat(Translate[0:3])
GradientReverse=np.mat(Translate[3:6])
AverageRefPos=np.mat(Translate[6]).reshape(3,1)
AverageCurrentPos=np.mat(Translate[7]).reshape(3,1)

# Changement de repere des points (DOWN vers UP)

PointE_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_0-AverageCurrentPos)+AverageRefPos
PointF_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_1-AverageCurrentPos)+AverageRefPos
PointG_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_2-AverageCurrentPos)+AverageRefPos
PointH_UP=((GradientReverse+np.eye(3,3)))*(CoordPoints_3-AverageCurrentPos)+AverageRefPos

print(PointE_UP)
print(PointF_UP)
print(PointG_UP)
print(PointH_UP)

[[ 169.26863068]
 [-167.23197847]
 [3538.66640453]]
[[2648.06535082]
 [-167.26173156]
 [3538.72590017]]
[[  169.3826608 ]
 [-2645.96177148]
 [ 3538.27230174]]
[[ 2648.17938094]
 [-2645.99152458]
 [ 3538.33179739]]


In [2]:
CoordPoints_0 = np.array([[170.], [-170.], [-1498.]])
CoordPoints_1 = np.array([[2649.], [-170.], [-1498.]])
CoordPoints_2 = np.array([[170.], [-2649.], [-1498.]])
CoordPoints_3 = np.array([[2649.], [-2649.], [-1498.]])
CoordPoints_4 = PointE_UP
CoordPoints_5 = PointF_UP
CoordPoints_6 = PointG_UP
CoordPoints_7 = PointH_UP

def SavePts(filename,pts) :
   f=open(filename,"wt")
   for i in range(len(pts)) :
       print ('%d %d %.3f %.3f %.3f'%(pts[i,0],pts[i,1],pts[i,2],pts[i,3],pts[i,4]),file=f)
   f.close()

def SavePtsfile(filename,pts,head) :
   f=open(filename,"wt")
   print ('%d %d %d %d'%(head[0],head[1],head[2],head[3]),file=f)
   for i in range(len(pts)) :
       print ('%d %d %.3f %.3f %.3f'%(pts[i,0],pts[i,1],pts[i,2],pts[i,3],pts[i,4]),file=f)
   f.close()

# Parametres de la Grille 
Nbcolonnes=32
Nblignes=32
NbPlans=64

# Generation des points selon vecteurs AC, BD, EG et FH 

VecteursLignes=np.reshape(([CoordPoints_2-CoordPoints_0, CoordPoints_3-CoordPoints_1, CoordPoints_6-CoordPoints_4,CoordPoints_7-CoordPoints_5]),(4,3))

OrigineVecteursLignes=np.reshape(([CoordPoints_0,CoordPoints_1,CoordPoints_4,CoordPoints_5]),(4,3))

PointsVecteurs=np.ones((Nblignes,4*3),float)

for i in range(0,Nblignes) :
  StepL=(i/(Nblignes-1))
  for j in range(0,4) :
    PointsVecteurs[i,j*3:(j*3)+3]=(VecteursLignes[j]*StepL)+ OrigineVecteursLignes[j]

	
# Generation des points de la grille correspondant aux surfaces Sup et inf du parallelogramme a partir des pts obtenues selon les vecteurs precedents

SurfaceUP=np.ones((Nblignes*Nbcolonnes,3),float)
SurfaceDOWN=np.ones((Nblignes*Nbcolonnes,3),float)

for i in range(0,Nblignes) :
    for j in range(0,Nbcolonnes) :
      StepC=(j/(Nbcolonnes-1))
      SurfaceUP[(i*Nblignes)+j,0:3]=((PointsVecteurs[i,3:6]-PointsVecteurs[i,0:3])*StepC)+PointsVecteurs[i,0:3]
      SurfaceDOWN[(i*Nblignes)+j,0:3]=((PointsVecteurs[i,9:12]-PointsVecteurs[i,6:9])*StepC)+PointsVecteurs[i,6:9]

# Generation de tous les points de la grille a partir des points des surfaces Sup et Inf 


VolumeUpDown=np.zeros((Nblignes*Nbcolonnes*NbPlans,5),float)

for i in range(0,NbPlans) :
    StepP=(i/(NbPlans-1))
    VolumeUpDown[i*Nblignes*Nbcolonnes:(i+1)*Nblignes*Nbcolonnes,2:5]=((SurfaceDOWN-SurfaceUP)*StepP)+SurfaceUP
    VolumeUpDown[i*Nblignes*Nbcolonnes:(i+1)*Nblignes*Nbcolonnes,0]=np.arange(Nblignes*Nbcolonnes)+(i*Nblignes*Nbcolonnes)+1


# Enregistrement fichier point grille Totale dans le referenticiel courant (UP)

HeadOfFile=list(np.reshape(np.asarray([len(VolumeUpDown),NbPlans,Nbcolonnes,Nblignes]), (1,np.size([len(VolumeUpDown),NbPlans,Nbcolonnes,Nblignes])))[0])

SavePtsfile('testgrilleTotaleUP.pts',VolumeUpDown,HeadOfFile)

In [3]:
# Enregistrement fichier point grille UP dans le referenticiel UP : Nbcolonnes*Nblignes x (19+16+15+14)
np0 = 19
np1 = 15 #+2
np2 = 15 #+2
np3 = 15 #+2

VolumeUP=VolumeUpDown[0:Nbcolonnes*Nblignes*np0,:]
VolumeDOWN1=VolumeUpDown[Nbcolonnes*Nblignes*(np0-2):Nbcolonnes*Nblignes*(np0+np1),:]
VolumeDOWN2=VolumeUpDown[Nbcolonnes*Nblignes*(np0+np1-2):Nbcolonnes*Nblignes*(np0+np1+np2),:]
VolumeDOWN3=VolumeUpDown[Nbcolonnes*Nblignes*(np0+np1+np2-2):,:]

# Enregistrement fichier point grille 0

HeadOfFile=list(np.reshape(np.asarray([len(VolumeUP),np0,Nbcolonnes,Nblignes]), ( 1,np.size([len(VolumeUP),np0,Nbcolonnes,Nblignes])))[0])
SavePtsfile('testgrille_0.pts',VolumeUP,HeadOfFile)

# Enregistrement fichier point grille 1-3

SavePts('testgrille_1.txt',VolumeDOWN1)
SavePts('testgrille_2.txt',VolumeDOWN2)
SavePts('testgrille_3.txt',VolumeDOWN3)

In [4]:
Grille_1=np.array((np.loadtxt('testgrille_1.txt')),dtype='float')
Grille_2=np.array((np.loadtxt('testgrille_2.txt')),dtype='float')
Grille_3=np.array((np.loadtxt('testgrille_3.txt')),dtype='float')

# ouverture fichier Translation genere a partir de la correlation entre 0-1: 
Translate=np.array((np.loadtxt('TranslationRef01.txt')),dtype='float')

Gradient=np.mat(Translate[0:3])
GradientReverse=np.mat(Translate[3:6])
AverageRefPos=np.mat(Translate[6]).reshape(3,1)
AverageCurrentPos=np.mat(Translate[7]).reshape(3,1)

# Changement de repere des points (UP vers DOWN)

Grille_1D=((Gradient+np.eye(3,3)))*(np.transpose(Grille_1[:,2:5])-AverageRefPos)+AverageCurrentPos
Grille_2D=((Gradient+np.eye(3,3)))*(np.transpose(Grille_2[:,2:5])-AverageRefPos)+AverageCurrentPos
Grille_3D=((Gradient+np.eye(3,3)))*(np.transpose(Grille_3[:,2:5])-AverageRefPos)+AverageCurrentPos

Grille_1DT=np.transpose(Grille_1D)

Grille_1DOW = Grille_1
Grille_1DOW[:,0] = Grille_1[:,0] - Nbcolonnes*Nblignes*(np0-2)
Grille_1DOW[:,2:5] = Grille_1DT

HeadOfFile=list(np.reshape(np.asarray([len(Grille_1DOW),np1+2,Nbcolonnes,Nblignes]), ( 1,np.size([len(Grille_1DOW),np1+2,Nbcolonnes,Nblignes])))[0])
SavePts('testgrille_1.txt',Grille_1DOW)
SavePtsfile('testgrille_1.pts',Grille_1DOW,HeadOfFile)

In [5]:
# ouverture fichier Translation genere a partir de la correlation entre 1-2: 
Translate=np.array((np.loadtxt('TranslationRef12.txt')),dtype='float')

Gradient=np.mat(Translate[0:3])
GradientReverse=np.mat(Translate[3:6])
AverageRefPos=np.mat(Translate[6]).reshape(3,1)
AverageCurrentPos=np.mat(Translate[7]).reshape(3,1)

# Changement de repere des points (UP vers DOWN)

Grille_2D=((Gradient+np.eye(3,3)))*(Grille_2D-AverageRefPos)+AverageCurrentPos
Grille_3D=((Gradient+np.eye(3,3)))*(Grille_3D-AverageRefPos)+AverageCurrentPos

Grille_2DT=np.transpose(Grille_2D)

Grille_2DOW = Grille_2
Grille_2DOW[:,0] = Grille_2[:,0] - Nbcolonnes*Nblignes*(np0+np1-2)
Grille_2DOW[:,2:5] = Grille_2DT

HeadOfFile=list(np.reshape(np.asarray([len(Grille_2DOW),np2+2,Nbcolonnes,Nblignes]), ( 1,np.size([len(Grille_2DOW),np2+2,Nbcolonnes,Nblignes])))[0])
SavePts('testgrille_2.txt',Grille_2DOW)
SavePtsfile('testgrille_2.pts',Grille_2DOW,HeadOfFile)

In [6]:
# ouverture fichier Translation genere a partir de la correlation entre 2-3: 
Translate=np.array((np.loadtxt('TranslationRef23.txt')),dtype='float')

Gradient=np.mat(Translate[0:3])
GradientReverse=np.mat(Translate[3:6])
AverageRefPos=np.mat(Translate[6]).reshape(3,1)
AverageCurrentPos=np.mat(Translate[7]).reshape(3,1)

# Changement de repere des points (UP vers DOWN)

Grille_3D=((Gradient+np.eye(3,3)))*(Grille_3D-AverageRefPos)+AverageCurrentPos
Grille_3DT=np.transpose(Grille_3D)

Grille_3DOW = Grille_3
Grille_3DOW[:,0] = Grille_3[:,0] - Nbcolonnes*Nblignes*(np0+np1+np2-2)
Grille_3DOW[:,2:5] = Grille_3DT

HeadOfFile=list(np.reshape(np.asarray([len(Grille_3DOW),np3+2,Nbcolonnes,Nblignes]), ( 1,np.size([len(Grille_3DOW),np3+2,Nbcolonnes,Nblignes])))[0])
SavePts('testgrille_3.txt',Grille_3DOW)
SavePtsfile('testgrille_3.pts',Grille_3DOW,HeadOfFile)

In [3]:
import numpy as np

point_reference = np.array((np.loadtxt('testgrille_0.txt')))

def SavePtsfile(filename,pts,head) :
   f=open(filename,"wt")
   print ('%d %d %d %d'%(head[0],head[1],head[2],head[3]),file=f)
   for i in range(len(pts)) :
       print ('%d %d %.3f %.3f %.3f'%(pts[i,0],pts[i,1],pts[i,2],pts[i,3],pts[i,4]),file=f)
   f.close()

x_c = 1420
y_c = -1440
r = 1250

for i in range(len(point_reference)):
    if (point_reference[i,2] - x_c)**2 + (point_reference[i,3] - y_c)**2 > r**2:
        point_reference[i,1] = -1

HeadOfFile=list(np.reshape(np.asarray([len(point_reference),19,32,32]), ( 1,np.size([len(point_reference),19,32,32])))[0])
SavePtsfile('Ref_Grille_0.pts',point_reference,HeadOfFile)

In [6]:
point_reference = np.array((np.loadtxt('testgrille_3.txt')))

x_c = 1420
y_c = -1440
r = 1250

for i in range(len(point_reference)):
    if (point_reference[i,2] - x_c)**2 + (point_reference[i,3] - y_c)**2 > r**2:
        point_reference[i,1] = -1
        
HeadOfFile=list(np.reshape(np.asarray([len(point_reference),17,32,32]), ( 1,np.size([len(point_reference),17,32,32])))[0])
SavePtsfile('Ref_Grille_3.pts',point_reference,HeadOfFile)